# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

jobs:
  test:
    working_directory: /app
    docker: 
      - image: cypress/included
    steps:
      - run : npx cypress run

workflows:
   test:
    jobs:
      - test
