# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
# version: 2.1

# jobs:
#   test:
#     working_directory: ~/app
#     docker: 
#       - image: cypress/included:3.4.0
#     steps:
#       - run : npx cypress run

# workflows:
#    test:
#     jobs:
#       - test

version: 2.1
orbs:
  cypress: cypress-io/cypress@1.28.0

jobs:
  build:
    - cypress/install
  run:
    - cypress/run:
      # context: Test_Credentials
      command: npx cypress run --env Username=$UserName,Password=$Password 
      requires:
        - cypress/install
      record: false
      parallel: true
      parallelism: 1


workflows:
  version: 2
  commit-workflow:
    jobs:
      - build
  nightly-job:
    triggers:
      - schedule:
        cron: "0 * * * *"
        filters:
          branches:
            only:
              - master
    job:
      - build
      - run

      

