# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
# version: 2.1

# jobs:
#   test:
#     working_directory: ~/app
#     docker: 
#       - image: cypress/included:3.4.0
#     steps:
#       - run : npx cypress run

# workflows:
#    test:
#     jobs:
#       - test

version: 2.1
orbs:
  cypress: cypress-io/cypress@1.0.1
workflows:
  build:
    jobs:
      - cypress/install
      - cypress/run:
          requires:
            - cypress/install
          record: false
          parallel: true
          parallelism: 4
          post-steps:
            - store_test_results:
                path: cypress/results
                path: test-results
                

